import { useState } from 'react'
import { ContentCard } from '../components/Cards'
import { Breadcrumbs } from '../components/UI'
import { claims, duplicateSuggestions, editorialEntities, evidence, evidenceCoverage, editorialSources, orphanReports, relationships, readiness } from '../generated'
import { PageFrame } from '../layouts/SiteLayout'
import type { WorkflowState } from '../types/editorial'
import { canTransition } from '../utils/editorialWorkflow'

export function EditorialRoutes({ path }: { path: string }) {
  if (path === '/editorial/sources') return <PageFrame title="Source dashboard" description="Internal editorial view of source coverage, rights and monitoring state."><EditorialSources /></PageFrame>
  if (path === '/editorial/review') return <PageFrame title="Review queue" description="Internal editorial worklist. These records are not public content."><ReviewQueue /></PageFrame>
  if (path === '/editorial/evidence') return <PageFrame title="Evidence coverage" description="Read-only editorial coverage report for claims, sources and evidence."><EvidenceCoveragePage /></PageFrame>
  const entityId = path.split('/').at(-1)
  const entity = editorialEntities.find((item) => item.id === entityId)
  if (!entity) return <PageFrame title="Editorial record not found" description="This record is not in the editorial registry."><Breadcrumbs current="Not found" /></PageFrame>
  return <PageFrame title={entity.title} description="Internal editorial workspace."><EditorialEntityPage entity={entity} preview={path.startsWith('/editorial/preview/')} /></PageFrame>
}

function EditorialSources() {
  const [filter, setFilter] = useState('All')
  const stats = { total: editorialSources.length, knownRights: editorialSources.filter((source) => source.copyrightStatus !== 'unknown').length, unknownRights: editorialSources.filter((source) => source.copyrightStatus === 'unknown').length }
  const filterMap: Record<string, string | undefined> = { All: undefined, Government: 'government', Academic: 'academic', Traditional: 'traditional-institution', 'Digital Library': 'digital-library', Manuscript: 'manuscript-archive', Other: 'other' }
  const visible = editorialSources.filter((source) => !filterMap[filter] || source.sourceType === filterMap[filter])
  return <div className="editorial-dashboard"><div className="card-grid"><ContentCard item={{ title: String(stats.total), description: 'Registered source records.', href: '/editorial/sources', eyebrow: 'Total sources' }} /><ContentCard item={{ title: String(stats.knownRights), description: 'Sources with recorded rights state.', href: '/editorial/sources', eyebrow: 'Rights recorded' }} /><ContentCard item={{ title: String(stats.unknownRights), description: 'Sources requiring rights review before reuse.', href: '/editorial/sources', eyebrow: 'Unknown rights' }} /></div><div className="filter-list" aria-label="Filter sources">{Object.keys(filterMap).map((option) => <button className={filter === option ? 'active' : ''} type="button" onClick={() => setFilter(option)} key={option}>{option}</button>)}</div><div className="entity-sections"><section><h2>Sources</h2>{visible.map((source) => <p key={source.id}><a href={`/sources/${source.id}`}>{source.name}</a> · {source.authorityLevel} · {source.copyrightStatus}</p>)}</section></div></div>
}

function ReviewQueue() { return <div className="editorial-dashboard"><div className="card-grid">{editorialEntities.filter((entity) => entity.status !== 'published').map((entity) => <ContentCard item={{ title: entity.title, description: `${entity.sourceIds.length} source(s) · ${entity.verification} · ${entity.publicationReadiness.blockers.length} blocker(s)`, href: `/editorial/content/${entity.type}/${entity.id}`, eyebrow: `${entity.type} · ${entity.status}` }} key={entity.id} />)}</div></div> }
function EvidenceCoveragePage() { return <div className="editorial-dashboard"><div className="card-grid"><ContentCard item={{ title: String(evidenceCoverage.filter((item) => item.statusLabel === 'STRONG').length), description: 'Records with evidence coverage.', href: '/editorial/evidence', eyebrow: 'Strong' }} /><ContentCard item={{ title: String(duplicateSuggestions.length), description: 'Duplicate or alias suggestions.', href: '/editorial/review', eyebrow: 'Quality suggestions' }} /></div><div className="entity-sections"><section><h2>Evidence coverage</h2>{evidenceCoverage.filter((item) => item.statusLabel !== 'NOT_APPLICABLE').map((item) => <p key={item.entityId}>{item.title} · {item.statusLabel} · {item.evidenceCount} evidence record(s)</p>)}</section><section><h2>Orphan diagnostics</h2>{orphanReports.filter((item) => item.classification !== 'VALID_ISOLATED_ENTITY').map((item) => <p key={item.entityId}>{item.title} · {item.classification}</p>)}</section></div></div> }
function EditorialEntityPage({ entity, preview }: { entity: (typeof editorialEntities)[number]; preview: boolean }) { const [state, setState] = useState<WorkflowState>((entity.workflowState as WorkflowState | undefined) ?? (entity.status === 'published' ? 'PUBLISHED' : 'DRAFT')); const currentReadiness = readiness[entity.id]; const entityClaims = claims.filter((claim) => claim.entityId === entity.id); const entityEvidence = evidence.filter((item) => item.entityId === entity.id); const nextStates = (['DISCOVERED', 'RESEARCHING', 'DRAFT', 'SOURCE_CHECK', 'EDITORIAL_REVIEW', 'TRADITIONAL_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED'] as WorkflowState[]).filter((next) => canTransition(state, next)); return <div className="editorial-workspace"><div className="preview-banner">{preview ? 'UNPUBLISHED / EDITORIAL PREVIEW' : 'INTERNAL EDITORIAL WORKSPACE'}</div><div className="entity-meta"><span>{entity.type}</span><span>{state}</span><span>{entity.verification}</span></div><p className="entity-description">{entity.description}</p><section className="entity-sections"><section><h2>Publication readiness</h2><p>{currentReadiness.publishable ? 'READY' : 'BLOCKED'} · {currentReadiness.blockers.length} blocker(s)</p>{currentReadiness.blockers.map((item) => <p key={item.code}>{item.message}</p>)}</section><section><h2>Claims & evidence</h2><p>{entityClaims.length} claim(s) · {entityEvidence.length} evidence record(s)</p></section><section><h2>Workflow</h2><div className="filter-list">{nextStates.map((next) => <button type="button" disabled={next === 'PUBLISHED' && !currentReadiness.publishable} onClick={() => setState(next)} key={next}>Move to {next}</button>)}</div></section><section><h2>Relationships</h2>{relationships.filter((relationship) => relationship.from === entity.id || relationship.to === entity.id).map((relationship) => <p key={relationship.id}>{relationship.relationship}: {relationship.from === entity.id ? relationship.to : relationship.from}</p>)}</section></section></div> }
