import { ContentCard } from '../components/Cards'
import { SearchBar, SectionHeader } from '../components/UI'
import { cultureCards } from '../data/concepts'
import { practiceCards } from '../data/practices'
import { entities as compiledEntities } from '../generated'
import { SiteLayout } from '../layouts/SiteLayout'

export function Home() {
  const publishedKnowledge = compiledEntities.filter((entity) => ['scripture', 'text', 'concept', 'glossary-term'].includes(entity.type))
  const beginnerIds = ['dharma', 'rigveda', 'upanishads', 'bhagavad-gita', 'karma', 'moksha', 'nyaya', 'puja']
  const beginnerEntities = beginnerIds.map((id) => compiledEntities.find((entity) => entity.id === id)).filter((entity): entity is (typeof compiledEntities)[number] => Boolean(entity))
  return <SiteLayout>
    <section className="hero"><div className="hero-grid container"><div className="hero-copy"><span className="eyebrow">A living archive · A place to begin</span><h1>Sanātana<br /><em>Dharma</em></h1><p className="hero-lead">A doorway into a living tradition of knowledge, philosophy, practice and culture.</p><p className="hero-supporting">Explore scriptures, philosophy, traditions, practices, festivals, temples, Sanskrit and the vast intellectual heritage of Sanātana Dharma.</p><div className="hero-actions"><a className="primary-button" href="/begin">Begin your journey <span aria-hidden="true">↗</span></a><a className="secondary-button" href="/library">Explore the library <span aria-hidden="true">↗</span></a></div></div><div className="hero-art" aria-label="Abstract manuscript-inspired line drawing" role="img"><div className="hero-arch" /><div className="hero-sun" /><div className="hero-line hero-line-one" /><div className="hero-line hero-line-two" /><span className="hero-script">ज्ञान</span><span className="hero-caption">knowledge · practice · culture</span></div></div></section>
    <section className="intro-band"><div className="container intro-grid"><div><span className="eyebrow">A thoughtful beginning</span><h2>Come with a question.<br /><em>Leave with a path.</em></h2></div><p>This is a growing, source-aware guide to the ideas, texts and practices of Sanātana Dharma. Start where your curiosity leads you, and take your time.</p></div></section>
    <section className="section container"><SectionHeader eyebrow="01 / Orientation" title="New to Sanātana Dharma?" description="Start here. Discover the fundamental ideas, texts and practices through a guided path." href="/begin" /><div className="question-grid">{beginnerEntities.map((entity, index) => <ContentCard item={{ title: entity.title, description: entity.description, href: `/${entity.type}/${entity.id}`, label: `0${index + 1}`, eyebrow: entity.classifications.join(' · ') }} key={entity.id} />)}</div></section>
    <section className="section section-tint"><div className="container"><SectionHeader eyebrow="02 / Knowledge" title="Explore the Knowledge" description="A living map of texts, ideas, language and traditions." href="/scriptures" />{publishedKnowledge.length ? <div className="card-grid knowledge-grid">{publishedKnowledge.map((entity) => <ContentCard item={{ title: entity.title, description: entity.description, href: `/${entity.type}/${entity.id}`, eyebrow: entity.classifications.join(' · ') }} key={entity.id} />)}</div> : <p className="empty-state">Knowledge records are being researched and reviewed before publication.</p>}</div></section>
    <section className="section hierarchy-section"><div className="container"><SectionHeader eyebrow="03 / Scripture" title="The scriptural universe" description="A hierarchy of textual worlds, rather than a catalogue where every tradition is flattened into one list." href="/scriptures" /><div className="hierarchy-grid"><div><span className="hierarchy-title">Śruti <small>that which is heard</small></span><div className="hierarchy-items">{['Vedas', 'Brāhmaṇas', 'Āraṇyakas', 'Upaniṣads'].map((item) => <a href="/scriptures" key={item}>{item}<span>↗</span></a>)}</div></div><div><span className="hierarchy-title">Smṛti <small>that which is remembered</small></span><div className="hierarchy-items">{['Itihāsa', 'Purāṇas', 'Dharmaśāstra', 'Other traditions'].map((item) => <a href="/scriptures" key={item}>{item}<span>↗</span></a>)}</div></div></div></div></section>
    <section className="practice-section"><div className="container"><SectionHeader eyebrow="04 / Living practice" title="Live the tradition" description="Structured placeholders for future, tradition-aware practice pages." href="/practice" /><div className="practice-grid">{practiceCards.map((item) => <ContentCard item={item} key={item.title} />)}</div></div></section>
    <section className="section container"><SectionHeader eyebrow="05 / Culture" title="Celebrate & discover" description="The wider worlds of place, performance, health, language and memory." href="/festivals" /><div className="culture-grid">{cultureCards.map((item) => <ContentCard item={item} key={item.title} />)}</div></section>
    <section className="library-feature"><div className="container library-feature-grid"><div><span className="eyebrow">06 / Collection</span><h2>The Sanātana Dharma <em>Library</em></h2><p>Discover texts, translations, manuscripts, recordings, research and trusted digital resources.</p><a className="primary-button" href="/library">Enter the library <span aria-hidden="true">↗</span></a></div><div className="library-stacks" aria-hidden="true"><span>TEXTS</span><span>TRANSLATIONS</span><span>RESEARCH</span></div></div></section>
    <section className="search-section"><div className="container narrow"><span className="eyebrow">07 / Search</span><h2>Follow the thread.</h2><p>Search scriptures, concepts, people and places as the portal grows.</p><SearchBar /><div className="example-searches"><span>Try</span>{['Rigveda', 'Bhagavad Gītā', 'Dharma', 'Krishna', 'Upanishads'].map((term) => <a href={`/search?q=${encodeURIComponent(term)}`} key={term}>{term}</a>)}</div></div></section>
    <section className="connections-section"><div className="container"><SectionHeader eyebrow="08 / Knowledge graph" title="Everything is connected" description="The portal will connect texts, concepts, people, traditions, practices, places and festivals." /><div className="connection-flow">{['Bhagavad Gītā', 'Mahābhārata', 'Dharma', 'Karma', 'Yoga', 'Mokṣa'].map((item, index) => <span key={item}><a href="/search">{item}</a>{index < 5 && <b aria-hidden="true">↓</b>}</span>)}</div></div></section>
    <section className="sources-band"><div className="container source-band-inner"><div><span className="eyebrow">09 / Trust</span><h2>Knowledge with sources.</h2><p>We believe sacred and historical knowledge deserves careful preservation. Our resources are organized with attention to primary texts, traditional sources, institutional repositories and scholarly research.</p></div><div className="source-links">{['Our Sources', 'Editorial Policy', 'Copyright', 'Methodology'].map((label) => <a href={label === 'Our Sources' ? '/sources' : '/about'} key={label}>{label} <span>↗</span></a>)}</div></div></section>
  </SiteLayout>
}
