import { lazy, Suspense, useEffect, useState } from 'react'
import './App.css'
import { ContentCard, SourceCard } from './components/Cards'
import { Breadcrumbs, RelatedContent, SearchBar } from './components/UI'
import { entities as compiledEntities, relationships as compiledRelationships, searchIndex as compiledSearchIndex, sources as compiledSources } from './generated'
import { libraryFilters, type LibraryFilter } from './data/library'
import { scriptureHierarchy } from './data/scriptures'
import { practiceCards } from './data/practices'
import { taxonomy } from './data/taxonomy'
import type { EntityRecord } from './types/knowledge'
import { Home } from './pages/Home'
import { PageFrame } from './layouts/SiteLayout'

const EditorialRoutes = lazy(() => import('./pages/EditorialRoutes').then((module) => ({ default: module.EditorialRoutes })))
const pages: Record<string, { title: string; description: string }> = {
  '/begin': { title: 'Begin Your Journey', description: 'A gentle orientation for first questions, key terms and the many ways into this living tradition.' },
  '/scriptures': { title: 'Scriptures', description: 'A growing map of texts, traditions and the contexts that help us read them carefully.' },
  '/philosophy': { title: 'Philosophy', description: 'Meet the questions and vocabulary of Indian philosophical traditions.' },
  '/practice': { title: 'Practice', description: 'Learn about practices in context, with attention to lineage, place and lived experience.' },
  '/festivals': { title: 'Festivals', description: 'A seasonal index of stories, observances and regional variations.' },
  '/temples': { title: 'Temples', description: 'A future directory of sacred places, their histories, communities and living practice.' },
  '/sanskrit': { title: 'Sanskrit', description: 'A first glossary of terms, texts and the language worlds they open.' },
  '/library': { title: 'The Sanātana Dharma Library', description: 'Texts, translations, manuscripts, recordings, research and trusted digital resources.' },
  '/search': { title: 'Search the portal', description: 'Find your next thread through the portal.' },
  '/sources': { title: 'Sources', description: 'A transparent register of references, editions and public digital resources.' },
  '/about': { title: 'About the project', description: 'A free and careful public knowledge platform, built in the open over time.' },
  '/research': { title: 'Research', description: 'A future index of scholarly research and institutional resources.' },
}
function App() {
  const path = window.location.pathname.replace(/\/$/, '') || '/'; const page = pages[path]
  useEffect(() => { const currentPage = pages[path]; const source = path.startsWith('/sources/') ? compiledSources.find((item) => item.id === path.split('/').at(-1)) : undefined; const entity = !path.startsWith('/editorial/') ? compiledEntities.find((item) => item.id === path.split('/').at(-1)) : undefined; document.title = path === '/' ? 'Sanātana Dharma | A living knowledge portal' : `${source?.name ?? entity?.title ?? currentPage?.title ?? 'Editorial workspace'} | Sanātana Dharma`; document.querySelector('meta[name="description"]')?.setAttribute('content', source?.description ?? entity?.description ?? currentPage?.description ?? 'Internal editorial workspace for the Sanātana Dharma knowledge portal.'); document.querySelector('meta[name="robots"]')?.setAttribute('content', path.startsWith('/editorial/') ? 'noindex,nofollow' : 'index,follow'); document.querySelector('link[rel="canonical"]')?.setAttribute('href', `${window.location.origin}${path}`) }, [path])
  if (path === '/') return <Home />
  if (path.startsWith('/editorial/')) return <Suspense fallback={<main className="container page-content" aria-live="polite">Loading editorial workspace...</main>}><EditorialRoutes path={path} /></Suspense>
  if (path === '/library') return <PageFrame title={pages['/library'].title} description={pages['/library'].description}><Breadcrumbs current="Library" /><LibraryPage /></PageFrame>
  if (path === '/search') return <PageFrame title={pages['/search'].title} description={pages['/search'].description}><Breadcrumbs current="Search" /><SearchPage /></PageFrame>
  if (path.startsWith('/knowledge/')) { const domain = path.split('/').at(-1)?.toUpperCase() ?? ''; return <PageFrame title={domain.replaceAll('_', ' ')} description={`Published knowledge classified under the ${domain.replaceAll('_', ' ').toLowerCase()} domain.`}><Breadcrumbs current={domain.replaceAll('_', ' ')} /><KnowledgeDomainPage domain={domain} /></PageFrame> }
  if (path === '/sources') return <PageFrame title="Sources" description={pages['/sources'].description}><Breadcrumbs current="Sources" /><div className="card-grid source-grid">{compiledSources.map((source) => <SourceCard key={source.id} source={{ id: source.id, title: source.name, publisher: source.organization, url: source.url, note: source.description }} />)}</div></PageFrame>
  if (path.startsWith('/sources/')) { const source = compiledSources.find((item) => item.id === path.split('/').at(-1)); return source ? <PageFrame title={source.name} description={source.description}><Breadcrumbs current={source.name} /><SourceProfile source={source} /></PageFrame> : <NotFound /> }
  const entity = compiledEntities.find((item) => item.id === path.split('/').filter(Boolean).at(-1)) as EntityRecord | undefined
  if (entity) return <PageFrame title={entity.title} description={entity.description}><Breadcrumbs current={entity.title} /><EntityPage entity={entity} /></PageFrame>
  if (page) return <PageFrame title={page.title} description={page.description}><PortalPage path={path} /></PageFrame>
  return <NotFound />
}
function NotFound() { return <PageFrame title="Page not found" description="This doorway has not been built yet."><Breadcrumbs current="Not found" /><RelatedContent links={[{ title: 'Scriptures', href: '/scriptures' }, { title: 'Begin your journey', href: '/begin' }]} /></PageFrame> }
function PortalPage({ path }: { path: string }) { if (path === '/begin') return <div className="question-grid">{compiledEntities.filter((entity) => entity.type === 'concept').map((entity, index) => <ContentCard key={entity.id} item={{ title: entity.title, description: entity.description, href: `/${entity.type}/${entity.id}`, label: `0${index + 1}` }} />)}</div>; if (path === '/scriptures' || path.startsWith('/scriptures/')) return <><div className="card-grid knowledge-grid">{compiledEntities.filter((entity) => ['scripture', 'text'].includes(entity.type)).map((entity) => <ContentCard item={{ title: entity.title, description: entity.description, href: `/${entity.type}/${entity.id}`, eyebrow: entity.classifications.join(' · ') }} key={entity.id} />)}</div><div className="hierarchy-grid page-hierarchy">{scriptureHierarchy.map((group) => <div key={group.title}><span className="hierarchy-title">{group.title} <small>{group.note}</small></span><div className="hierarchy-items">{group.items.map((item) => <a href="/scriptures" key={item}>{item}<span>↗</span></a>)}</div></div>)}</div></>; if (path === '/practice') return <div className="practice-grid">{practiceCards.map((item) => <ContentCard item={item} key={item.title} />)}</div>; const concepts = compiledEntities.filter((entity) => entity.type === 'concept'); return <div className="card-grid">{concepts.map((entity) => <ContentCard key={entity.id} item={{ title: entity.title, description: entity.description, href: `/${entity.type}/${entity.id}`, eyebrow: entity.classifications.join(' · ') }} />)}</div> }
function LibraryPage() { const [filter, setFilter] = useState<LibraryFilter>('All'); const [query, setQuery] = useState(''); const items = compiledEntities.filter((entity) => ['book', 'manuscript', 'article', 'audio-resource', 'video-resource'].includes(entity.type) && (filter === 'All' || entity.classifications.some((item) => item.toLowerCase() === filter.toLowerCase())) && `${entity.title} ${entity.description}`.toLowerCase().includes(query.toLowerCase())); return <div className="library-page"><div className="library-controls"><div className="filter-list" aria-label="Filter library">{libraryFilters.map((item) => <button className={filter === item ? 'active' : ''} type="button" onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><SearchBar compact value={query} onQueryChange={setQuery} placeholder="Search the library..." /></div><div className="card-grid library-grid">{items.map((item) => <ContentCard item={{ title: item.title, description: item.description, href: `/${item.type}/${item.id}`, eyebrow: item.classifications.join(' · ') }} key={item.id} />)}</div>{!items.length && <p className="empty-state">No published library records match that search yet.</p>}</div> }
function SearchPage() { const [query, setQuery] = useState(new URLSearchParams(window.location.search).get('q') ?? ''); const term = query.trim().toLowerCase(); const results = compiledSearchIndex.map((item) => { const title = item.title.toLowerCase(); const aliases = item.aliases.map((alias) => alias.toLowerCase()); const score = !term ? 0 : title === term ? 100 : aliases.includes(term) ? 90 : title.startsWith(term) ? 70 : aliases.some((alias) => alias.startsWith(term)) ? 60 : title.includes(term) ? 40 : item.description.toLowerCase().includes(term) ? 20 : 0; return { item, score } }).filter((result) => result.score > 0).sort((a, b) => b.score - a.score); return <div className="search-page"><SearchBar value={query} onQueryChange={setQuery} placeholder="Search scriptures, concepts, people, places..." /><div className="card-grid search-results">{results.map(({ item }) => <ContentCard item={{ title: item.title, description: item.description, href: `/${item.type}/${item.id}`, eyebrow: item.classification.join(' · ') }} key={item.id} />)}</div></div> }
function EntityPage({ entity }: { entity: EntityRecord }) { const related = compiledRelationships.filter((relationship) => relationship.from === entity.id || relationship.to === entity.id); return <div className="entity-page"><div className="entity-meta"><span>{entity.type}</span><span>{entity.status}</span><span>{entity.language.join(' · ')}</span></div><p className="entity-description">{entity.description}</p><div className="entity-sections"><section><h2>Classifications</h2><p>{entity.classifications.map((item) => <a href={`/knowledge/${item.toLowerCase()}`} key={item}>{item} </a>)}</p></section><section><h2>Related knowledge</h2>{related.map((relationship) => { const id = relationship.from === entity.id ? relationship.to : relationship.from; const target = compiledEntities.find((item) => item.id === id); return target ? <p key={relationship.id}><a href={`/${target.type}/${target.id}`}>{target.title}</a> · {relationship.relationship}</p> : null })}</section><section><h2>Sources</h2><p>{entity.sourceIds.join(' · ')}</p></section></div></div> }
function KnowledgeDomainPage({ domain }: { domain: string }) { const items = compiledEntities.filter((entity) => entity.classifications.some((item) => item.toUpperCase() === domain)); return <div className="knowledge-domain-page"><p className="empty-state">{items.length} published entries in this domain.</p>{items.length ? <div className="card-grid">{items.map((entity) => <ContentCard item={{ title: entity.title, description: entity.description, href: `/${entity.type}/${entity.id}`, eyebrow: entity.type }} key={entity.id} />)}</div> : <RelatedContent links={taxonomy.slice(0, 5).map((item) => ({ title: item, href: `/knowledge/${item.toLowerCase()}` }))} />}</div> }
function SourceProfile({ source }: { source: (typeof compiledSources)[number] }) { return <div className="source-profile"><div className="entity-meta"><span>{source.sourceType}</span><span>{source.authorityLevel}</span><span>{source.copyrightStatus}</span></div><div className="entity-sections"><section><h2>Scope</h2><p>{source.description}</p></section><section><h2>Rights</h2><p>{source.license}</p><p>{source.reuseAllowed ? 'Reuse permitted as recorded.' : 'Link only unless rights are verified.'}</p></section><section><h2>Use in this portal</h2><p>{(source.howWeUse ?? ['reference']).join(' · ')}</p><a className="text-link" href={source.url} target="_blank" rel="noreferrer">Open official source ↗</a></section></div></div> }
export default App
